name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: git config --global user.name = "Your Name"
      - run: git config --global user.email = "your@mail"
      - run: pip install mkdocs-material #устанавливаем тему Material
      - run: pip install mkdocs-print-site-plugin #устанавливаем плагин для пдф https://timvink.github.io/mkdocs-print-site-plugin/index.html
      - run: mkdocs gh-deploy --force
      - run: git fetch
      - run: pip install mike
      - run: mike deploy --push --update-aliases -b gh-pages 4.0 latest
      

